# Generated by Django 6.0.6 on 2026-09-29 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_support_number', models.CharField(default='+880 1334-317864', help_text='Active WhatsApp customer support number with country code', max_length=50)),
                ('whatsapp_default_message', models.CharField(default='Hello OneMed Support, I need assistance with an order.', help_text='Pre-filled default message when user clicks WhatsApp link', max_length=255)),
                ('is_whatsapp_enabled', models.BooleanField(default=True, help_text='Toggle WhatsApp support button visibility across consumer portal')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'db_table': 'system_settings',
            },
        ),
    ]
